improve error reporting

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -21,6 +21,7 @@
 
 VERSION=2
 SERVICE="Nextcloud"
+ERROR_FILE=$(getarg "--error-file")
 
 . /usr/share/univention-join/joinscripthelper.lib
 . /usr/share/univention-appcenter/joinscripthelper.sh
@@ -61,6 +62,25 @@ nextcloud_main() {
     detect_onlyoffice
     joinscript_save_current_version
     exit 0
+}
+
+error_msg() {
+    if [ -n "$1" ]; then
+        IN="$@"
+    else
+        read IN # from stdin
+    fi
+	if [ -n "$ERROR_FILE" ]; then
+		echo "$IN" | tee -a "$ERROR_FILE" >&2
+	else
+		echo "$IN" >&2
+	fi
+}
+
+
+die() {
+	error_msg "$@"
+	exit 1
 }
 
 nextcloud_appliance_detection() {
@@ -257,7 +277,7 @@ nextcloud_ensure_extended_attributes () {
     univention-directory-manager settings/extended_attribute modify "$@" \
         --dn "cn=nextcloudUserEnabled,cn=nextcloud,cn=custom attributes,cn=univention,$ldap_base" \
         --set tabAdvanced='1' \
-        --set default="1" || die
+        --set default="1" || die "Could not modify nextcloudUserEnabled extended attribute"
 
     univention-directory-manager settings/extended_attribute create "$@" \
         --position "cn=nextcloud,cn=custom attributes,cn=univention,$ldap_base" --set module="users/user" \
@@ -285,7 +305,7 @@ nextcloud_ensure_extended_attributes () {
         --set hook='None' || \
     univention-directory-manager settings/extended_attribute modify "$@" \
         --dn "cn=nextcloudUserQuota,cn=nextcloud,cn=custom attributes,cn=univention,$ldap_base" \
-        --set tabAdvanced='1' || die
+        --set tabAdvanced='1' || die "Could not modify nextcloudUserQuota extended attribute"
 
     univention-directory-manager settings/extended_attribute create "$@" \
         --position "cn=nextcloud,cn=custom attributes,cn=univention,$ldap_base" --set module="groups/group" \
@@ -313,7 +333,7 @@ nextcloud_ensure_extended_attributes () {
         --set hook='None' || \
     univention-directory-manager settings/extended_attribute modify "$@" \
         --dn "cn=nextcloudGroupEnabled,cn=nextcloud,cn=custom attributes,cn=univention,$ldap_base" \
-        --set tabAdvanced='1' || die
+        --set tabAdvanced='1' || die "Could not modify nextcloudGroupEnabled extended attribute"
 }
 
 # Enables all Users that fit the filter to access Nextcloud
@@ -339,7 +359,7 @@ nextcloud_import_ucs_certificates () {
 }
 
 nextcloud_mark_initial_conig_done() {
-    touch "$NC_PERMCONFDIR/initial_config_done" || die
+    touch "$NC_PERMCONFDIR/initial_config_done" || die "Could not touch initial config flag"
 }
 
 nextcloud_curl() {
@@ -353,7 +373,7 @@ nextcloud_curl() {
         if [ "$nextcloud_ucs_debug" -eq 1 ]; then
             debugOutput=", parameters were\n\t$@"
         fi
-        echo "curl failed with error $curlCode$debugOutput" > /dev/stderr
+        error_msg "curl failed with error $curlCode$debugOutput"
         exit ${curlCode}
     fi
     echo "$result"
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -19,13 +19,28 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+ERROR_FILE=$(getarg "--error-file")
+
+error_msg() {
+    if [ -n "$1" ]; then
+        IN="$@"
+    else
+        read IN # from stdin
+    fi
+	if [ -n "$ERROR_FILE" ]; then
+		echo "$IN" | tee -a "$ERROR_FILE" >&2
+	else
+		echo "$IN" >&2
+	fi
+}
+
 NC_DATADIR="$NC_PERMDATADIR/nextcloud-data"
 NC_UCR_FILE="$NC_PERMCONFDIR/ucr"
 
 cd /var/www/html
 if [ ! -x occ ]; then
-	echo "occ missing or not executable"
-	exit 1
+	error_msg "/var/www/html/occ missing or not executable – was the docker container modified manually?"
+	exit 21
 fi
 
 OCC="sudo -u www-data ./occ"
@@ -55,12 +70,13 @@ if [ "$NC_IS_INSTALLED" -eq 0 ] ; then
         --database-name "$DB_NAME" \
         --database-user "$DB_USER" \
         --database-pass "$DB_PASSWORD" \
-        --data-dir      "$NC_DATADIR"
+        --data-dir      "$NC_DATADIR" \
+        2>&1 | error_msg
 
     STATE=$?
     if [[ $STATE != 0 ]]; then
-        echo  "Error while installing Nextcloud"
-        exit 1;
+        error_msg  "Error while installing Nextcloud. Please check the apache log within the Nextcloud docker container, and (if existing) the nextcloud.log file in $NC_DATADIR."
+        exit 22;
     fi
 fi
 
@@ -69,6 +85,7 @@ $OCC check
 $OCC status
 $OCC app:list
 $OCC upgrade 2>&1>> "$UPGRADE_LOGFILE"
+error_msg "The upgrade log is written to $UPGRADE_LOGFILE within the nextcloud container"
 
 # basic Nextcloud configuration
 eval "`cat \"$NC_UCR_FILE\"`"
@@ -132,7 +149,7 @@ else
     # attempt to re-enable disabled apps
     DISABLED_APPS=( $(cat "$UPGRADE_LOGFILE" | grep "Disabled incompatible app:" | cut -d ":" -f 2 | egrep -o "[a-z]+[a-z0-9_]*[a-z0-9]+") )
     for APPID in "${DISABLED_APPS[@]}" ; do
-        $OCC app:enable "$APPID" || echo "Could not re-enable $APPID"
+        $OCC app:enable "$APPID" || error_msg "Could not re-enable $APPID"
     done
 fi
 
